import {
  Product,
  SellerProfile,
  UserProfile,
  Order,
  Coupon,
  NotificationItem,
  MarketplaceSettings,
  CommissionTransaction,
  ProductReview,
} from './types';

export const INITIAL_SETTINGS: MarketplaceSettings = {
  commissionRatePercent: 5,
  platformUpiId: '7880265898@ybl', // Platform settlement UPI ID (Confidential, for Admin ledger only)
  freeDeliveryThreshold: 499,
  standardDeliveryFee: 49,
  isCodEnabled: true,
  supportPhone: '+91 1800 200 8899',
  supportEmail: 'support@paigammart.in',
};

export const INITIAL_SELLERS: SellerProfile[] = [
  {
    id: 'seller_1',
    userId: 'user_seller_1',
    businessName: 'Varanasi Silk & Weaves Emporium',
    legalEntityName: 'Varanasi Silk Emporium Private Limited',
    email: 'contact@varanasiweaves.in',
    phone: '+91 98234 11223',
    category: 'Ethnic Wear & Sarees',
    rating: 4.8,
    totalRatingsCount: 342,
    kyc: {
      panNumber: 'AAACV1234F',
      gstNumber: '09AAACV1234F1Z8',
      businessAddress: 'D-48/132 Godowlia Chowk, Varanasi, Uttar Pradesh - 221001',
      bankAccountName: 'Varanasi Silk Emporium Pvt Ltd',
      bankAccountNumber: '91802001928374',
      bankIfscCode: 'SBIN0001234',
      bankName: 'State Bank of India',
      upiId: 'varanasiweaves@oksbi',
      status: 'verified',
      submittedAt: '2026-08-10T10:00:00.000Z',
      verifiedAt: '2026-08-11T14:30:00.000Z',
    },
    isApproved: true,
    isBlocked: false,
    totalOrdersFulfilled: 289,
    grossSales: 485000,
    platformCommissionDeducted: 24250, // 5%
    netEarnings: 460750,
    pendingSettlement: 18500,
    completedSettlement: 442250,
    joinedDate: '2026-08-10',
  },
  {
    id: 'seller_2',
    userId: 'user_seller_2',
    businessName: 'Kumbakonam Brass & Metal Artisans',
    legalEntityName: 'Kumbakonam Traditional Craft Guild',
    email: 'crafts@kumbakonambrass.in',
    phone: '+91 94432 99881',
    category: 'Traditional Handcrafts & Brass',
    rating: 4.9,
    totalRatingsCount: 188,
    kyc: {
      panNumber: 'BBBCK9876G',
      gstNumber: '33BBBCK9876G1ZC',
      businessAddress: '14 Big Bazaar Street, Kumbakonam, Tamil Nadu - 612001',
      bankAccountName: 'Kumbakonam Craft Guild',
      bankAccountNumber: '50100492817263',
      bankIfscCode: 'HDFC0000456',
      bankName: 'HDFC Bank',
      upiId: 'kumbabrass@okhdfcbank',
      status: 'verified',
      submittedAt: '2026-08-15T11:00:00.000Z',
      verifiedAt: '2026-08-16T16:00:00.000Z',
    },
    isApproved: true,
    isBlocked: false,
    totalOrdersFulfilled: 142,
    grossSales: 215000,
    platformCommissionDeducted: 10750, // 5%
    netEarnings: 204250,
    pendingSettlement: 8900,
    completedSettlement: 195350,
    joinedDate: '2026-08-15',
  },
  {
    id: 'seller_3',
    userId: 'user_seller_3',
    businessName: 'Jodhpur Heritage Leathercraft',
    legalEntityName: 'Marwar Leather Guild LLP',
    email: 'info@jodhpurleather.in',
    phone: '+91 97845 22334',
    category: 'Leather & Accessories',
    rating: 4.7,
    totalRatingsCount: 215,
    kyc: {
      panNumber: 'CCCLJ4567H',
      gstNumber: '08CCCLJ4567H1ZA',
      businessAddress: 'Plot 22, Mandore Industrial Area, Jodhpur, Rajasthan - 342001',
      bankAccountName: 'Marwar Leather Guild LLP',
      bankAccountNumber: '3819283746510',
      bankIfscCode: 'ICIC0000789',
      bankName: 'ICICI Bank',
      upiId: 'jodhpurleather@icici',
      status: 'verified',
      submittedAt: '2026-08-20T09:00:00.000Z',
      verifiedAt: '2026-08-21T10:00:00.000Z',
    },
    isApproved: true,
    isBlocked: false,
    totalOrdersFulfilled: 178,
    grossSales: 340000,
    platformCommissionDeducted: 17000, // 5%
    netEarnings: 323000,
    pendingSettlement: 12400,
    completedSettlement: 310600,
    joinedDate: '2026-08-20',
  },
  {
    id: 'seller_4',
    userId: 'user_seller_4',
    businessName: 'Himalayan Harvest & Organic Spices',
    legalEntityName: 'Pahadi Agro Natural Produce',
    email: 'care@himalayanproduce.in',
    phone: '+91 98112 55667',
    category: 'Gourmet, Spices & Dry Fruits',
    rating: 4.9,
    totalRatingsCount: 512,
    kyc: {
      panNumber: 'DDDKH8899K',
      gstNumber: '05DDDKH8899K1Z4',
      businessAddress: 'Mall Road, Manali, Himachal Pradesh - 175131',
      bankAccountName: 'Pahadi Agro Natural Produce',
      bankAccountNumber: '627192837401',
      bankIfscCode: 'PUNB0123456',
      bankName: 'Punjab National Bank',
      upiId: 'himalayanspices@axisbank',
      status: 'pending', // Demo pending verification for Admin panel!
      submittedAt: '2026-10-01T15:20:00.000Z',
      notes: 'New seller awaiting PAN and GST document verification',
    },
    isApproved: false, // For admin to approve in test flow!
    isBlocked: false,
    totalOrdersFulfilled: 0,
    grossSales: 0,
    platformCommissionDeducted: 0,
    netEarnings: 0,
    pendingSettlement: 0,
    completedSettlement: 0,
    joinedDate: '2026-10-01',
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod_1',
    sellerId: 'seller_1',
    sellerBusinessName: 'Varanasi Silk & Weaves Emporium',
    title: 'Handcrafted Pure Chanderi Silk Saree with Gold Zari Border',
    brand: 'Varanasi Heritage',
    category: 'Ethnic Wear & Sarees',
    subcategory: 'Silk Sarees',
    description:
      'Woven by master artisans in Chanderi, this saree blends pure mulberry silk and mercerized cotton with intricate golden zari buttis. Lightweight, breathable, and radiating regal Indian craftsmanship, it includes an unstitched matching blouse piece (0.8m).',
    specifications: {
      Fabric: 'Pure Chanderi Silk & Cotton Blend',
      Length: '5.5 Meters + 0.8 Meter Blouse Piece',
      Weave: 'Handloom Jacquard with Fine Zari',
      Care: 'Dry Clean Only',
      Occasion: 'Festive, Wedding & Celebrations',
      Origin: 'Chanderi / Varanasi, India',
    },
    mrp: 5999,
    price: 3299,
    discountPercent: 45,
    stock: 18,
    sku: 'SAR-CHN-001',
    images: [
      '/src/assets/images/product_chanderi_saree_1791034659208.jpg',
      '/src/assets/images/hero_marketplace_lifestyle_1791034646293.jpg',
    ],
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    variants: [
      { id: 'v1_gold', name: 'Royal Gold & Emerald', color: 'Gold / Emerald', sku: 'SAR-CHN-001-GE', price: 3299, mrp: 5999, stock: 12 },
      { id: 'v1_ruby', name: 'Ruby Crimson & Zari', color: 'Ruby Crimson', sku: 'SAR-CHN-001-RC', price: 3499, mrp: 6299, stock: 6 },
    ],
    rating: 4.8,
    reviewCount: 148,
    badge: 'Bestseller',
    returnPolicyDays: 7,
    isCodAvailable: true,
    freeDeliveryThreshold: 499,
    isActive: true,
    createdAt: '2026-08-12T12:00:00.000Z',
  },
  {
    id: 'prod_2',
    sellerId: 'seller_2',
    sellerBusinessName: 'Kumbakonam Brass & Metal Artisans',
    title: 'Authentic South Indian Brass Filter Coffee Maker & Davarah Set (Degree Kaapi)',
    brand: 'Kumbakonam Brassworks',
    category: 'Traditional Handcrafts & Brass',
    subcategory: 'Kitchen & Dining',
    description:
      'Handcrafted heavy-gauge virgin brass South Indian filter coffee maker with matching traditional Davarah and Tumbler. Tin-lined (Kalai) for optimum aroma and pure authentic South Indian decoction brewing.',
    specifications: {
      Material: '100% Solid Brass with Traditional Finish',
      Capacity: '250 ml (Makes 3-4 cups of strong decoction)',
      Included: '1 Percolator + Press Disc + Lid + 1 Davarah + 1 Tumbler',
      Weight: '620 grams (Heavy Gauge)',
      Craftsmanship: 'Hand-turned by Kumbakonam Coppersmith Guild',
      Origin: 'Kumbakonam, Tamil Nadu',
    },
    mrp: 2499,
    price: 1399,
    discountPercent: 44,
    stock: 35,
    sku: 'BRS-KAP-002',
    images: [
      '/src/assets/images/product_brass_filter_coffee_1791034670597.jpg',
    ],
    variants: [
      { id: 'v2_2cup', name: '2 Cups (150ml)', size: '150ml', sku: 'BRS-KAP-150', price: 1199, mrp: 1999, stock: 15 },
      { id: 'v2_4cup', name: '4 Cups (250ml)', size: '250ml', sku: 'BRS-KAP-250', price: 1399, mrp: 2499, stock: 20 },
    ],
    rating: 4.9,
    reviewCount: 92,
    badge: 'Artisanal Pick',
    returnPolicyDays: 10,
    isCodAvailable: true,
    freeDeliveryThreshold: 499,
    isActive: true,
    createdAt: '2026-08-18T10:00:00.000Z',
  },
  {
    id: 'prod_3',
    sellerId: 'seller_3',
    sellerBusinessName: 'Jodhpur Heritage Leathercraft',
    title: 'Full-Grain Vegetable Tanned Leather 15.6" Laptop Messenger Bag',
    brand: 'Marwar Leather',
    category: 'Leather & Accessories',
    subcategory: 'Bags & Briefcases',
    description:
      'Artisanal handcrafted leather satchel engineered from sturdy full-grain hide. Features padded laptop sleeve up to 15.6 inches, heavy-duty antique brass fittings, YKK zippers, adjustable shoulder strap, and natural oil tanning that ages with a rich vintage patina.',
    specifications: {
      Material: '100% Full Grain Buffalo Leather',
      Dimensions: '16 x 12 x 4.5 Inches',
      Compartments: '1 Padded Laptop Section, 2 Pen Slots, 1 Zipper Pocket, 2 External Gusset Pockets',
      Hardware: 'Solid Brass Buckles & Rivets',
      Strap: 'Detachable 55-inch Padded Ergonomic Leather Strap',
      Origin: 'Jodhpur, Rajasthan',
    },
    mrp: 7499,
    price: 3899,
    discountPercent: 48,
    stock: 14,
    sku: 'LTH-MSG-003',
    images: [
      '/src/assets/images/product_leather_messenger_1791034681503.jpg',
    ],
    variants: [
      { id: 'v3_tan', name: 'Vintage Saddle Tan', color: 'Saddle Tan', sku: 'LTH-MSG-TAN', price: 3899, mrp: 7499, stock: 8 },
      { id: 'v3_brown', name: 'Deep Espresso Brown', color: 'Espresso Brown', sku: 'LTH-MSG-ESP', price: 3999, mrp: 7799, stock: 6 },
    ],
    rating: 4.7,
    reviewCount: 84,
    badge: 'Top Rated',
    returnPolicyDays: 7,
    isCodAvailable: true,
    freeDeliveryThreshold: 499,
    isActive: true,
    createdAt: '2026-08-22T14:30:00.000Z',
  },
  {
    id: 'prod_4',
    sellerId: 'seller_1',
    sellerBusinessName: 'Varanasi Silk & Weaves Emporium',
    title: 'Banarasi Brocade Silk Kurta & Dhoti Trouser Set for Men',
    brand: 'Varanasi Heritage',
    category: 'Ethnic Wear & Sarees',
    subcategory: 'Mens Ethnic',
    description:
      'Luxurious pure spun silk festive kurta styled with ornate Banarasi weave along the mandarin collar and placket. Comes with tailored comfortable drawstring dhoti trousers.',
    specifications: {
      Fabric: 'Art Silk Blend with Brocade Collar',
      Fit: 'Comfort Regular Festive Fit',
      Sleeves: 'Full Sleeve with Folded Cuffs',
      Length: 'Knee Length',
      Origin: 'Varanasi, India',
    },
    mrp: 4999,
    price: 2499,
    discountPercent: 50,
    stock: 22,
    sku: 'KRT-BAN-004',
    images: [
      '/src/assets/images/hero_marketplace_lifestyle_1791034646293.jpg',
    ],
    variants: [
      { id: 'v4_m', name: 'Size 38 (M)', size: '38 (M)', sku: 'KRT-38-M', price: 2499, mrp: 4999, stock: 8 },
      { id: 'v4_l', name: 'Size 40 (L)', size: '40 (L)', sku: 'KRT-40-L', price: 2499, mrp: 4999, stock: 9 },
      { id: 'v4_xl', name: 'Size 42 (XL)', size: '42 (XL)', sku: 'KRT-42-XL', price: 2499, mrp: 4999, stock: 5 },
    ],
    rating: 4.6,
    reviewCount: 67,
    returnPolicyDays: 7,
    isCodAvailable: true,
    freeDeliveryThreshold: 499,
    isActive: true,
    createdAt: '2026-08-25T11:00:00.000Z',
  },
  {
    id: 'prod_5',
    sellerId: 'seller_2',
    sellerBusinessName: 'Kumbakonam Brass & Metal Artisans',
    title: 'Handcrafted Brass Diya Oil Lamp Set (Pair of 2 - 8 Inch Height)',
    brand: 'Kumbakonam Brassworks',
    category: 'Traditional Handcrafts & Brass',
    subcategory: 'Pooja Essentials',
    description:
      'Traditional Mayur Peacock brass diya lamps crafted with exquisite hand carving. Perfect for daily prayer, Diwali festivities, and traditional home entrances.',
    specifications: {
      Material: 'Virgin Brass',
      Height: '8 Inches each',
      Weight: '1.2 kg per pair',
      Origin: 'Tamil Nadu, India',
    },
    mrp: 1899,
    price: 999,
    discountPercent: 47,
    stock: 40,
    sku: 'BRS-DYA-005',
    images: [
      '/src/assets/images/product_brass_filter_coffee_1791034670597.jpg',
    ],
    rating: 4.9,
    reviewCount: 112,
    badge: 'Festive Special',
    returnPolicyDays: 7,
    isCodAvailable: true,
    freeDeliveryThreshold: 499,
    isActive: true,
    createdAt: '2026-08-28T09:15:00.000Z',
  },
  {
    id: 'prod_6',
    sellerId: 'seller_3',
    sellerBusinessName: 'Jodhpur Heritage Leathercraft',
    title: 'Handcrafted Classic Leather Bifold Wallet with RFID Protection',
    brand: 'Marwar Leather',
    category: 'Leather & Accessories',
    subcategory: 'Wallets',
    description:
      'Slim profile vegetable-tanned genuine leather wallet featuring 8 card slots, 2 currency compartments, dedicated coin pocket, and aerospace-grade RFID blocking liner.',
    specifications: {
      Material: 'Vegetable Tanned Cowhide',
      Features: 'RFID Blocking Layer, Hidden SIM Slot',
      Dimensions: '11 x 9 x 1.5 cm',
      Origin: 'Jodhpur, Rajasthan',
    },
    mrp: 1499,
    price: 699,
    discountPercent: 53,
    stock: 50,
    sku: 'LTH-WLT-006',
    images: [
      '/src/assets/images/product_leather_messenger_1791034681503.jpg',
    ],
    variants: [
      { id: 'v6_tan', name: 'Tan Brown', color: 'Tan Brown', sku: 'WLT-TAN', price: 699, mrp: 1499, stock: 25 },
      { id: 'v6_blk', name: 'Midnight Black', color: 'Midnight Black', sku: 'WLT-BLK', price: 699, mrp: 1499, stock: 25 },
    ],
    rating: 4.7,
    reviewCount: 154,
    returnPolicyDays: 7,
    isCodAvailable: true,
    freeDeliveryThreshold: 499,
    isActive: true,
    createdAt: '2026-09-01T15:00:00.000Z',
  },
];

export const INITIAL_USER: UserProfile = {
  id: 'cust_rajesh',
  name: 'Rajesh Singh',
  email: 'rajeshsinghpaigamji2012@gmail.com',
  phone: '+91 98765 43210',
  role: 'customer',
  joinedDate: '2026-08-01',
  savedAddresses: [
    {
      id: 'addr_1',
      fullName: 'Rajesh Singh',
      phone: '+91 98765 43210',
      pincode: '400050',
      addressLine1: 'Flat 402, Sea Pearl Heights, Bandra West',
      addressLine2: 'Near Hill Road Market',
      city: 'Mumbai',
      state: 'Maharashtra',
      landmark: 'Opposite Mehboob Studio',
      addressType: 'home',
      isDefault: true,
    },
    {
      id: 'addr_2',
      fullName: 'Rajesh Singh (Office)',
      phone: '+91 98765 43210',
      pincode: '400051',
      addressLine1: 'Unit 8B, Tech Park One, BKC G Block',
      city: 'Mumbai',
      state: 'Maharashtra',
      addressType: 'work',
      isDefault: false,
    },
  ],
  wishlist: ['prod_2', 'prod_3'],
};

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord_101',
    orderNumber: 'PM-2026-8812',
    customerId: 'cust_rajesh',
    customerName: 'Rajesh Singh',
    customerEmail: 'rajeshsinghpaigamji2012@gmail.com',
    customerPhone: '+91 98765 43210',
    shippingAddress: INITIAL_USER.savedAddresses[0],
    items: [
      {
        productId: 'prod_2',
        sellerId: 'seller_2',
        sellerBusinessName: 'Kumbakonam Brass & Metal Artisans',
        title: 'Authentic South Indian Brass Filter Coffee Maker & Davarah Set',
        image: '/src/assets/images/product_brass_filter_coffee_1791034670597.jpg',
        price: 1399,
        mrp: 2499,
        quantity: 1,
        selectedVariant: '4 Cups (250ml)',
        platformCommissionRate: 0.05,
        platformCommissionAmount: 69.95, // 5% of 1399
        sellerSettlementAmount: 1329.05, // 95%
      },
    ],
    subtotal: 1399,
    discount: 100,
    deliveryFee: 0, // Free over 499
    taxAmount: 0,
    totalAmount: 1299,
    appliedCouponCode: 'FIRSTBUY',
    paymentMethod: 'upi',
    paymentStatus: 'paid',
    paymentTransactionId: 'UPI-TXN-9821827419',
    paymentDetails: {
      upiVpa: 'rajesh@okhdfcbank',
      gatewayRef: 'PG-RAZOR-99120',
    },
    orderStatus: 'delivered',
    orderDate: '2026-09-28T14:20:00.000Z',
    estimatedDeliveryDate: '2026-10-01',
    deliveredDate: '2026-10-01T16:45:00.000Z',
    courierName: 'BlueDart Express India',
    courierTrackingNumber: 'BD-8899210214',
    trackingSteps: [
      {
        status: 'order_placed',
        title: 'Order Placed',
        description: 'Order PM-2026-8812 verified and confirmed.',
        timestamp: '2026-09-28 14:20',
        completed: true,
      },
      {
        status: 'confirmed',
        title: 'Order Confirmed by Seller',
        description: 'Kumbakonam Brass Artisans accepted the order.',
        timestamp: '2026-09-28 15:00',
        completed: true,
      },
      {
        status: 'packed',
        title: 'Packed & Dispatched',
        description: 'Item safely packaged with tamper-proof seal.',
        timestamp: '2026-09-29 11:30',
        completed: true,
      },
      {
        status: 'shipped',
        title: 'Shipped via BlueDart',
        description: 'In transit from Chennai Hub to Mumbai Hub.',
        timestamp: '2026-09-30 08:45',
        completed: true,
      },
      {
        status: 'out_for_delivery',
        title: 'Out for Delivery',
        description: 'Delivery associate Manoj K. is arriving at your address.',
        timestamp: '2026-10-01 10:15',
        completed: true,
      },
      {
        status: 'delivered',
        title: 'Delivered',
        description: 'Delivered to Rajesh Singh at Bandra West, Mumbai.',
        timestamp: '2026-10-01 16:45',
        completed: true,
      },
    ],
    totalPlatformCommission: 69.95,
    totalSellerPayable: 1329.05,
    settlementStatus: 'settled',
    settlementDate: '2026-10-02',
  },
  {
    id: 'ord_102',
    orderNumber: 'PM-2026-9041',
    customerId: 'cust_rajesh',
    customerName: 'Rajesh Singh',
    customerEmail: 'rajeshsinghpaigamji2012@gmail.com',
    customerPhone: '+91 98765 43210',
    shippingAddress: INITIAL_USER.savedAddresses[0],
    items: [
      {
        productId: 'prod_1',
        sellerId: 'seller_1',
        sellerBusinessName: 'Varanasi Silk & Weaves Emporium',
        title: 'Handcrafted Pure Chanderi Silk Saree with Gold Zari Border',
        image: '/src/assets/images/product_chanderi_saree_1791034659208.jpg',
        price: 3299,
        mrp: 5999,
        quantity: 1,
        selectedVariant: 'Royal Gold & Emerald',
        platformCommissionRate: 0.05,
        platformCommissionAmount: 164.95, // 5% of 3299
        sellerSettlementAmount: 3134.05, // 95%
      },
    ],
    subtotal: 3299,
    discount: 329.9,
    deliveryFee: 0,
    taxAmount: 0,
    totalAmount: 2969.1,
    appliedCouponCode: 'PAIGAM10',
    paymentMethod: 'card',
    paymentStatus: 'paid',
    paymentTransactionId: 'CARD-TXN-110293847',
    paymentDetails: {
      cardLast4: '4392',
      bankName: 'HDFC Bank RuPay Platinum',
      gatewayRef: 'PG-PAYU-440192',
    },
    orderStatus: 'shipped',
    orderDate: '2026-10-02T10:15:00.000Z',
    estimatedDeliveryDate: '2026-10-05',
    courierName: 'Delhivery Surface Logistics',
    courierTrackingNumber: 'DEL-99120485',
    trackingSteps: [
      {
        status: 'order_placed',
        title: 'Order Placed',
        description: 'Order PM-2026-9041 placed with RuPay card.',
        timestamp: '2026-10-02 10:15',
        completed: true,
      },
      {
        status: 'confirmed',
        title: 'Order Confirmed',
        description: 'Varanasi Silk Emporium confirmed item availability.',
        timestamp: '2026-10-02 11:00',
        completed: true,
      },
      {
        status: 'packed',
        title: 'Packed',
        description: 'Securely packaged in silk preservation bag.',
        timestamp: '2026-10-02 17:30',
        completed: true,
      },
      {
        status: 'shipped',
        title: 'In Transit',
        description: 'Departed Varanasi Sorting Hub heading towards Mumbai.',
        timestamp: '2026-10-03 04:20',
        completed: true,
      },
      {
        status: 'out_for_delivery',
        title: 'Out for Delivery',
        description: 'Scheduled for local delivery.',
        timestamp: 'Pending',
        completed: false,
      },
      {
        status: 'delivered',
        title: 'Delivered',
        description: 'Delivery confirmation.',
        timestamp: 'Pending',
        completed: false,
      },
    ],
    totalPlatformCommission: 164.95,
    totalSellerPayable: 3134.05,
    settlementStatus: 'pending',
  },
];

export const INITIAL_COUPONS: Coupon[] = [
  {
    id: 'coup_1',
    code: 'PAIGAM10',
    description: 'Get 10% instant discount up to ₹500 on all orders above ₹999',
    discountType: 'percentage',
    discountValue: 10,
    minOrderValue: 999,
    maxDiscount: 500,
    validUntil: '2026-12-31',
    usageLimit: 10000,
    timesUsed: 1420,
    isActive: true,
  },
  {
    id: 'coup_2',
    code: 'FIRSTBUY',
    description: 'Flat ₹150 discount for our new valued customers on min cart ₹499',
    discountType: 'fixed',
    discountValue: 150,
    minOrderValue: 499,
    validUntil: '2026-12-31',
    usageLimit: 50000,
    timesUsed: 6240,
    isActive: true,
  },
  {
    id: 'coup_3',
    code: 'FESTIVE500',
    description: 'Flat ₹500 off on festive orders exceeding ₹2,499',
    discountType: 'fixed',
    discountValue: 500,
    minOrderValue: 2499,
    validUntil: '2026-11-15',
    usageLimit: 5000,
    timesUsed: 890,
    isActive: true,
  },
];

export const INITIAL_COMMISSIONS: CommissionTransaction[] = [
  {
    id: 'comm_1',
    orderId: 'ord_101',
    orderNumber: 'PM-2026-8812',
    sellerId: 'seller_2',
    sellerBusinessName: 'Kumbakonam Brass & Metal Artisans',
    grossAmount: 1399,
    commissionRate: 0.05,
    commissionAmount: 69.95, // 5%
    gatewayFee: 0,
    taxesDeducted: 0,
    netSellerAmount: 1329.05,
    platformAccountUpi: '7880265898@ybl', // Private platform settlement UPI
    sellerAccountInfo: 'Kumbakonam Craft Guild (A/C: ...7263 / IFSC: HDFC0000456)',
    status: 'settled',
    createdAt: '2026-09-28T14:20:00.000Z',
    settledAt: '2026-10-02T10:00:00.000Z',
  },
  {
    id: 'comm_2',
    orderId: 'ord_102',
    orderNumber: 'PM-2026-9041',
    sellerId: 'seller_1',
    sellerBusinessName: 'Varanasi Silk & Weaves Emporium',
    grossAmount: 3299,
    commissionRate: 0.05,
    commissionAmount: 164.95, // 5%
    gatewayFee: 0,
    taxesDeducted: 0,
    netSellerAmount: 3134.05,
    platformAccountUpi: '7880265898@ybl',
    sellerAccountInfo: 'Varanasi Silk Emporium (A/C: ...8374 / IFSC: SBIN0001234)',
    status: 'recorded',
    createdAt: '2026-10-02T10:15:00.000Z',
  },
];

export const INITIAL_REVIEWS: ProductReview[] = [
  {
    id: 'rev_1',
    productId: 'prod_2',
    userId: 'cust_rajesh',
    userName: 'Rajesh S.',
    rating: 5,
    title: 'Pure authentic Kumbakonam brass! Makes divine filter kaapi',
    comment:
      'The brass is heavy gauge, shiny, and the tin lining inside is done to perfection. The decoction comes out thick and aromatic just like in traditional South Indian homes. Delivery by BlueDart was fast and packaging was secure.',
    verifiedPurchase: true,
    helpfulCount: 24,
    createdAt: '2026-10-02T09:00:00.000Z',
  },
  {
    id: 'rev_2',
    productId: 'prod_1',
    userId: 'cust_ananya',
    userName: 'Ananya Mukherjee',
    rating: 5,
    title: 'Breathtaking weave and genuine Chanderi silk feel',
    comment:
      'Bought this for Durga Puja festivities. The gold zari has a subtle, rich glow without being gaudy. Very comfortable to drape for long hours.',
    verifiedPurchase: true,
    helpfulCount: 38,
    createdAt: '2026-09-20T14:10:00.000Z',
  },
  {
    id: 'rev_3',
    productId: 'prod_3',
    userId: 'cust_vikram',
    userName: 'Vikramaditya Roy',
    rating: 5,
    title: 'Superb leather craftsmanship, authentic Jodhpur quality',
    comment:
      'Fits my 15.6 inch Dell laptop with room to spare for charger and notebooks. The natural leather smell and antique brass buckles give it a classy executive look.',
    verifiedPurchase: true,
    helpfulCount: 19,
    createdAt: '2026-09-25T11:45:00.000Z',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif_1',
    recipientId: 'cust_rajesh',
    title: 'Order Delivered! 🎉',
    message: 'Your order PM-2026-8812 (Brass Filter Coffee Maker) has been delivered. Share your review!',
    type: 'order',
    link: 'orders',
    isRead: false,
    createdAt: '2026-10-01T16:46:00.000Z',
  },
  {
    id: 'notif_2',
    recipientId: 'seller_1',
    title: 'New Order Received #PM-2026-9041',
    message: 'You have a new order for Chanderi Silk Saree. Gross: ₹3,299 | 5% Commission: ₹164.95.',
    type: 'order',
    link: 'seller-orders',
    isRead: false,
    createdAt: '2026-10-02T10:16:00.000Z',
  },
  {
    id: 'notif_3',
    recipientId: 'admin',
    title: 'KYC Verification Pending',
    message: 'Seller "Himalayan Harvest & Organic Spices" submitted KYC documents for review.',
    type: 'kyc',
    link: 'admin-sellers',
    isRead: false,
    createdAt: '2026-10-01T15:21:00.000Z',
  },
];
